[package]
name = "solana-rust-hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.8.14"

[dev-dependencies]
solana-sdk = "1.8.14"

[lib]
crate-type = ["cdylib", "lib"]
